### PR TITLE
Implement an input switch

### PR DESCRIPTION
**Pull request by stevenguh**
This is a rough WIP of the switches for input like `-n` in logging and also a foundation structure for #41. I just want to make sure this approach is okay with @kahole.

### CODE REVIEW

**Comment by kahole** [comment]
Will look into this soon, been busy lately.

**Comment by kahole** [comment]
@stevenguh sorry for the late response here.

This looks great. It meshes with the existing switch menu system.
We can move forward with this.

We could maybe split the input switches out on their own menu item, and separate menu. Sort of like in Emacs magit.
```
a   Log references
-   Switches [ --graph ]
=  Options [ -n256 ]
```
In fact I think maybe this is the only way to fit all the switches and options for logging :)

**Comment by stevenguh** [comment]
I remember there was a weird bug with this that I needed to fix (it was something like the menu store last operation because we didn't create those switch every time), so I wouldn't say this is complete. However, I don't have time in the next two weeks. Feel free work on this if you have more time in the short term.

**Comment by kahole** [comment]
Actively working on this

**Pull request closed without merging**
