### PR TITLE
Fix the command mode in VSCode Vim (#24)

### PR DESCRIPTION
**Pull request by stevenguh**

### CODE REVIEW

**Comment by stevenguh** [comment]
The last commit uses regular expression to match anything but `SearchInProgressMode` and `CommandlineInProgress, and effectively that's `!=` without using two separate statements. Let me know what you think, I can revert the regex change.

See https://stackoverflow.com/a/37988661/2563765 for the regex

**Comment by kahole** [comment]
Good fix, I'm just gonna give it some time as I'm not certain it's the only way yet. And every time edamagit updates its keybindings everyone's custom bindings break 😸

**Comment by stevenguh** [comment]
I agree, let's sit on it and see if there is a better solution

**Comment by stevenguh** [comment]
The more I think about this. The more I think the vscode vim issue may not be handled in this repo.

**Comment by kahole** [comment]
Any suggestions on what can be done / made instead?
I feel the level of support is decent now, you know, except the not-merged command mode compatability.

**Comment by stevenguh** [comment]
I am thinking move all the vim stuff to another extension (like `eval-edamgit`) that [bundles](https://code.visualstudio.com/api/references/extension-manifest#extension-packs) this extension. This allows an overrides keybindings specifies on that repo only. So it doesn't feel like pollting the main repo. And document well how to override keybindings in the main repo.

**Comment by stevenguh** [comment]
Overall I think the current solution works well; however, there are still some inconveniences that I think it may be outside of the scope of this repo.
1. Command mode
2. `y` will trigger another menu in spacemacs
image
3. `y` in visual mode

Especially implementing the second in the main repo seems like a pollution. I am thinking that the second point can be handled by other extension to reroute to a quickpick menu.

**Comment by kahole** [comment]
Sounds great, that would be perfect.

Gave it a go here, although I can't get the overrides to work:
I've added the 'negative' keybindings, and it installs fine, but those keys still are bound to the magit actions.

https://github.com/kahole/evil-edamagit

**Comment by stevenguh** [comment]
That was just a concept. Maybe it doesn't work with the current form extension pack.

I tried the extension pack, for some reason it doesn't install the `edmagit` when I install the `evil-edamagit`.
The second approach is to have the extension pack install and detect keybinding on extnesion load, or on command trigger.

**Comment by kahole** [comment]
> That was just a concept. Mayb....

Oh, ok, I misunderstood.

> I tried the extension pack, for some reason it doesn't install the edmagit when I install the evil-edamagit.

Strange.. it does here. Maybe try restarting?

Will look into options. We have essentially solved it, including command mode.

**Comment by kahole** [comment]
> The third option, of course it's to maintain a fork just for the keybinding.

I will do that if all else fails (maybe just a branch, will see), and publish in lock-step with edamagit.

**Comment by stevenguh** [comment]
> Oh, ok, I misunderstood.

Sorry for not being clearer. I hoped that would worked.

> Strange.. it does here. Maybe try restarting?

I can install the extension pack, but yeah, the key bindings don't work. default key binding doesn't really let people 

> Will look into options. We have essentially solved it, including command mode (and probably y in visual mode by expanding the regex and adding another binding).

Right, for `y` we can probably do something similar to exclude `Visual.*` mode

> Other extensions can do stuff on 'y' if they like, that doesn't have anything to do with supporting VSCodeVim)

I was hoping there is cleaner way to handle it without having this repo explicit handle stuff related to other extensions. 

> I will do that if all else fails (maybe just a branch, will see), and publish in lock-step with edamagit.

Right there are many ways to do this. As long as the main and the evil are in sync, it's all good.

**Comment by stevenguh** [comment]
Yep. I agree. I hadn't thought of that case. That defects the use case of the another extension.

I like those new changes!! It basically solves most of my current pain points⭐️Thank you for pushing the change😊Another small issue is that since I closely follow this repo, so I know you updated the keybindings. For others, I suspect it would a bit shocking that they current key bindings don't work anymore.

Something I thought it would nice is a breaking change notification, the extension will create a vscode notification when there's a breaking change after the vs code automatically updated the extension. However, vscode is not making that easy, most people are implementing something hacky like https://github.com/stevenguh/spacecode/blob/master/src/extension.ts#L45-L49

I think this extension could implement something like this when people active the extension. Since this extension is not activated on launch (I like this being not activated on launch), it might still misses some cases. Anyway, this is not related to this thread.

**Pull request closed without merging**
