### PR TITLE
Makes helpView dynamic by parsing user keybindings (#24)

### PR DESCRIPTION
**Pull request by kahole**

### CODE REVIEW

**Comment by stevenguh** [comment]
I think that's a really cool way to get the user keybinding; however, I feel like this way of getting around of lack of API might be a bit too smart. 

These are some of the problems I see with this approach:
- Needs to handle multiple keys assigned to the same command
- Need to make sure the user keybinding fetching works in environment like VSCode Remote, and vscode with [own user space](https://stackoverflow.com/questions/49667641/launch-vsc-with-clean-or-custom-profile) or [Portable mode](https://code.visualstudio.com/docs/editor/portable)
- The json parse doesn't work quite well especially with the comment stripping. I can imagine this being solved by importing a jsonc parser that handle all edge cases of comments in json. However, it increases the bundle size.
- The help text display `shift+1` instead of `!` (easy fix)

Although, as much as I like the help text be auto generated, I think there is a lot of things need to be flushed out simply due to the lack of API from vscode. I also think this approach is not mutually exclusive to the manually configuration approach, but I think we should [keep it simple](https://en.wikipedia.org/wiki/KISS_principle)

**Comment by kahole** [comment]
1. Is pretty simple. Just list multiple or grab last one, which is effectively done now. 
2. Already taken care of. LogPath is in `user-data-dir`.
3. Comment stripping is not perfect, yes, but its a good start.
4. `shift+1` is not guaranteed to be '!'. E.g. `shift+4` is not `$` with Norwegian keyboard layout.

Worst case it falls back on defaults. It's only a help view after all.

**Comment by stevenguh** [comment]
This probably solves most of the problems if it works well enough. I am wondering if there is a place for an escape hatch like a manual override (configuration) so `it  can solve number 4.
For example: it will display `!` instead `shift+1` or `_` instead of `shift+-`?

**Comment by kahole** [comment]
I understand your concern. Esthetically, I agree its better.
Although, I think the underlying problem here is the way VSCode handles keybindings vs Emacs. In VSCode, sadly, it is not possible to assign a command to `$`, e.g.
This leads me to think edamagit should embrace the VSCode style bindings, rather than fight them.
Maybe something can be done to make it look better in the Help view itself.

**Comment by stevenguh** [comment]
That makes sense to not flight the way vscode capture keys especially with different keyboard layout. I understand it's probably better to display `shift+-` for example to be accurate for different keyboards.

One small esthetic improvement is to the limit the number of column in the help text to 3, so the text is not just as easy to wrap around. (Right now, the workspace is wrapping to the next line for me with this change) Also, I wish we can open the editor in row instead of column, but it seems like there isn't really an API for it?

Incorporating config would help the last bit of the esthetic issue, but I guess it could be a bit like everywhere.
```typescript
let binds = meta.contributes.keybindings.reduce((prev, bind) => ({
  ...prev,
  [bind.command]: HelpView.keybindingToDisplayKey(bind.key)
}), {});

binds = userKeyBindings.reduce((prev: any, bind: any) => ({
  ...prev,
  [bind.command]: HelpView.keybindingToDisplayKey(bind.key)
}), binds);

binds = helpKeyConfig.reduce((prev: any, bind: any) => ({
  ...prev,
  [bind.command]: HelpView.keybindingToDisplayKey(bind.key)
}), binds);
```

**Comment by stevenguh** [comment]
jsonc parser example:
https://github.com/microsoft/vscode-python/pull/7281/files

**Pull request merged**
